from dataclasses import dataclass


class DataInjectionArtifact:
    feature_store_file_path 
class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModelTrainerArtifact:...
class ModelEvaluateArtifact:...
class ModelPusherArtifact:...