class DataInjectionArtifact:
    pass
class DataValidationArtifact:...
class DataTransformationArtifact:...
class ModelTrainerArtifact:...
class ModelEvaluateArtifact:...
class ModelPusherArtifact:...